#include "UeremcpEdGraphReader.h"

#include "EdGraph/EdGraph.h"
#include "EdGraph/EdGraphNode.h"
#include "EdGraph/EdGraphPin.h"
#include "EdGraphSchema_K2.h"
#include "Misc/DateTime.h"
#include "Misc/EngineVersion.h"

namespace UeremcpEdGraphReader
{
	static FString ContainerTypeToString(const EPinContainerType Container)
	{
		switch (Container)
		{
		case EPinContainerType::Array: return TEXT("array");
		case EPinContainerType::Set: return TEXT("set");
		case EPinContainerType::Map: return TEXT("map");
		default: return TEXT("none");
		}
	}

	static bool DefaultIsExecPin(const UEdGraphPin* Pin)
	{
		return Pin && Pin->PinType.PinCategory == UEdGraphSchema_K2::PC_Exec;
	}

	static TSharedPtr<FJsonValue> PinDefaultToJson(const UEdGraphPin* Pin)
	{
		if (!Pin->DefaultObject)
		{
			if (!Pin->DefaultValue.IsEmpty())
			{
				return MakeShared<FJsonValueString>(Pin->DefaultValue);
			}
			if (!Pin->AutogeneratedDefaultValue.IsEmpty())
			{
				return MakeShared<FJsonValueString>(Pin->AutogeneratedDefaultValue);
			}
			return nullptr;
		}

		return MakeShared<FJsonValueString>(Pin->DefaultObject->GetPathName());
	}

	static void ComputeReachability(
		const UEdGraph* Graph,
		const FUeremcpEdGraphSemanticHooks& Hooks,
		TSet<const UEdGraphNode*>& OutReachable)
	{
		TArray<const UEdGraphNode*> Queue;
		if (Hooks.GatherEntryNodes)
		{
			Queue = Hooks.GatherEntryNodes(Graph);
		}

		while (Queue.Num() > 0)
		{
			const UEdGraphNode* Node = Queue.Pop(EAllowShrinking::No);
			if (!Node || OutReachable.Contains(Node))
			{
				continue;
			}

			OutReachable.Add(Node);

			for (const UEdGraphPin* Pin : Node->Pins)
			{
				if (!Pin)
				{
					continue;
				}

				for (const UEdGraphPin* Linked : Pin->LinkedTo)
				{
					if (Linked && Linked->GetOwningNode())
					{
						Queue.Add(Linked->GetOwningNode());
					}
				}
			}
		}
	}

	static void FindDisconnectedSubgraphs(
		const UEdGraph* Graph,
		const TSet<const UEdGraphNode*>& Reachable,
		const TMap<const UEdGraphNode*, FString>& NodeIds,
		TArray<TArray<FString>>& OutSubgraphs)
	{
		TSet<const UEdGraphNode*> Unreachable;
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			if (!Reachable.Contains(Node))
			{
				Unreachable.Add(Node);
			}
		}

		while (Unreachable.Num() > 0)
		{
			const UEdGraphNode* Seed = nullptr;
			for (const UEdGraphNode* Node : Unreachable)
			{
				Seed = Node;
				break;
			}

			if (!Seed)
			{
				break;
			}

			TSet<const UEdGraphNode*> Component;
			TArray<const UEdGraphNode*> Stack;
			Stack.Add(Seed);

			while (Stack.Num() > 0)
			{
				const UEdGraphNode* Node = Stack.Pop(EAllowShrinking::No);
				if (!Node || !Unreachable.Contains(Node) || Component.Contains(Node))
				{
					continue;
				}

				Component.Add(Node);
				Unreachable.Remove(Node);

				for (const UEdGraphPin* Pin : Node->Pins)
				{
					if (!Pin)
					{
						continue;
					}

					for (const UEdGraphPin* Linked : Pin->LinkedTo)
					{
						if (Linked && Linked->GetOwningNode())
						{
							Stack.Add(Linked->GetOwningNode());
						}
					}
				}
			}

			TArray<FString> Island;
			for (const UEdGraphNode* Node : Component)
			{
				if (const FString* Id = NodeIds.Find(Node))
				{
					Island.Add(*Id);
				}
			}
			Island.Sort();
			if (Island.Num() > 0)
			{
				OutSubgraphs.Add(MoveTemp(Island));
			}
		}
	}

	static FString FormatEngineVersionString()
	{
		const FEngineVersion& Version = FEngineVersion::Current();
		return FString::Printf(TEXT("%u.%u.%u"), Version.GetMajor(), Version.GetMinor(), Version.GetPatch());
	}
}

using namespace UeremcpEdGraphReader;

FString FUeremcpEdGraphReader::MakeNodeId(const UEdGraphNode* Node)
{
	return FString::Printf(TEXT("n%s"), *Node->NodeGuid.ToString(EGuidFormats::Digits));
}

FString FUeremcpEdGraphReader::MakePinId(const UEdGraphPin* Pin)
{
	return FString::Printf(TEXT("p%s"), *Pin->PinId.ToString(EGuidFormats::Digits));
}

TSharedPtr<FJsonObject> FUeremcpEdGraphReader::PinTypeToJson(const FEdGraphPinType& PinType)
{
	TSharedPtr<FJsonObject> Obj = MakeShared<FJsonObject>();
	Obj->SetStringField(TEXT("category"), PinType.PinCategory.ToString());
	if (!PinType.PinSubCategory.IsNone())
	{
		Obj->SetStringField(TEXT("sub_category"), PinType.PinSubCategory.ToString());
	}
	if (PinType.PinSubCategoryObject.IsValid())
	{
		Obj->SetStringField(TEXT("sub_category_object"), PinType.PinSubCategoryObject->GetPathName());
	}
	Obj->SetStringField(TEXT("container"), ContainerTypeToString(PinType.ContainerType));
	if (PinType.bIsReference)
	{
		Obj->SetBoolField(TEXT("is_reference"), true);
	}
	if (PinType.bIsConst)
	{
		Obj->SetBoolField(TEXT("is_const"), true);
	}
	return Obj;
}

bool FUeremcpEdGraphReader::ReadGraph(
	const UEdGraph* Graph,
	const FUeremcpEdGraphReadOptions& Options,
	const FUeremcpEdGraphSemanticHooks& Hooks,
	FUeremcpEdGraphReadResult& OutResult)
{
	OutResult = FUeremcpEdGraphReadResult();

	if (!Graph)
	{
		OutResult.Error = TEXT("graph is null");
		return false;
	}

	const auto ResolveSemanticType = [&Hooks](const UEdGraphNode* Node) -> FString
	{
		if (Hooks.ResolveSemanticType)
		{
			return Hooks.ResolveSemanticType(Node);
		}
		return Node->GetClass()->GetName();
	};

	const auto ResolveSemanticId = [&Hooks](const UEdGraphNode* Node) -> FString
	{
		if (Hooks.ResolveSemanticId)
		{
			return Hooks.ResolveSemanticId(Node);
		}
		return FString();
	};

	const auto ResolveProperties = [&Hooks](const UEdGraphNode* Node) -> TSharedPtr<FJsonObject>
	{
		if (Hooks.ResolveProperties)
		{
			return Hooks.ResolveProperties(Node);
		}
		TSharedPtr<FJsonObject> Props = MakeShared<FJsonObject>();
		Props->SetStringField(TEXT("type_id"), Node->GetClass()->GetName());
		return Props;
	};

	const auto IsEntryNode = [&Hooks](const UEdGraphNode* Node) -> bool
	{
		return Hooks.IsEntryNode ? Hooks.IsEntryNode(Node) : false;
	};

	const auto IsExecPinFn = [&Hooks](const UEdGraphPin* Pin) -> bool
	{
		if (Hooks.IsExecPin)
		{
			return Hooks.IsExecPin(Pin);
		}
		return DefaultIsExecPin(Pin);
	};

	TMap<const UEdGraphNode*, FString> NodeIds;
	for (UEdGraphNode* Node : Graph->Nodes)
	{
		NodeIds.Add(Node, MakeNodeId(Node));
	}

	TArray<TSharedPtr<FJsonValue>> NodeArray;
	TArray<TSharedPtr<FJsonValue>> LinkArray;

	if (Options.bEmitNodesAndLinks)
	{
		for (UEdGraphNode* Node : Graph->Nodes)
		{
			TSharedPtr<FJsonObject> NodeObj = MakeShared<FJsonObject>();
			const FString& NodeId = NodeIds[Node];
			NodeObj->SetStringField(TEXT("node_id"), NodeId);

			const FString SemanticId = ResolveSemanticId(Node);
			if (!SemanticId.IsEmpty())
			{
				NodeObj->SetStringField(TEXT("semantic_id"), SemanticId);
			}

			NodeObj->SetStringField(TEXT("node_class"), Node->GetClass()->GetName());
			NodeObj->SetStringField(TEXT("semantic_type"), ResolveSemanticType(Node));
			NodeObj->SetStringField(TEXT("title"), Node->GetNodeTitle(ENodeTitleType::FullTitle).ToString());
			{
				TArray<TSharedPtr<FJsonValue>> Pos;
				Pos.Add(MakeShared<FJsonValueNumber>(Node->NodePosX));
				Pos.Add(MakeShared<FJsonValueNumber>(Node->NodePosY));
				NodeObj->SetArrayField(TEXT("position"), Pos);
			}

			NodeObj->SetObjectField(TEXT("properties"), ResolveProperties(Node));

			if (!Node->NodeComment.IsEmpty())
			{
				NodeObj->SetStringField(TEXT("comment"), Node->NodeComment);
			}

			TArray<TSharedPtr<FJsonValue>> InputPins;
			TArray<TSharedPtr<FJsonValue>> OutputPins;
			TSharedPtr<FJsonObject> Defaults = MakeShared<FJsonObject>();

			for (UEdGraphPin* Pin : Node->Pins)
			{
				if (!Pin)
				{
					continue;
				}

				TSharedPtr<FJsonObject> PinObj = MakeShared<FJsonObject>();
				PinObj->SetStringField(TEXT("pin_id"), MakePinId(Pin));
				PinObj->SetStringField(TEXT("name"), Pin->PinName.ToString());
				PinObj->SetStringField(
					TEXT("direction"),
					Pin->Direction == EGPD_Input ? TEXT("input") : TEXT("output"));
				PinObj->SetObjectField(TEXT("pin_type"), PinTypeToJson(Pin->PinType));

				if (Pin->PinType.PinSubCategoryObject.IsValid())
				{
					OutResult.DependencyPaths.Add(Pin->PinType.PinSubCategoryObject->GetPathName());
				}

				if (Options.bIncludePinDefaults)
				{
					if (TSharedPtr<FJsonValue> DefaultVal = PinDefaultToJson(Pin))
					{
						Defaults->SetField(Pin->PinName.ToString(), DefaultVal);
						PinObj->SetField(TEXT("default_value"), DefaultVal);
					}
				}

				TArray<TSharedPtr<FJsonValue>> PinLinks;
				for (const UEdGraphPin* Linked : Pin->LinkedTo)
				{
					if (!Linked || !Linked->GetOwningNode())
					{
						continue;
					}

					const UEdGraphNode* OtherNode = Linked->GetOwningNode();
					TSharedPtr<FJsonObject> LinkRef = MakeShared<FJsonObject>();
					LinkRef->SetStringField(TEXT("node_id"), NodeIds[OtherNode]);
					LinkRef->SetStringField(TEXT("pin_id"), MakePinId(Linked));
					PinLinks.Add(MakeShared<FJsonValueObject>(LinkRef));

					if (Pin->Direction == EGPD_Output)
					{
						TSharedPtr<FJsonObject> Edge = MakeShared<FJsonObject>();
						Edge->SetStringField(TEXT("from_node"), NodeId);
						Edge->SetStringField(TEXT("from_pin"), Pin->PinName.ToString());
						Edge->SetStringField(TEXT("to_node"), NodeIds[OtherNode]);
						Edge->SetStringField(TEXT("to_pin"), Linked->PinName.ToString());
						Edge->SetStringField(TEXT("kind"), IsExecPinFn(Pin) ? TEXT("exec") : TEXT("data"));
						Edge->SetBoolField(TEXT("valid"), true);
						LinkArray.Add(MakeShared<FJsonValueObject>(Edge));
					}
				}

				if (PinLinks.Num() > 0)
				{
					PinObj->SetArrayField(TEXT("links"), PinLinks);
				}

				if (Pin->Direction == EGPD_Input)
				{
					InputPins.Add(MakeShared<FJsonValueObject>(PinObj));
				}
				else
				{
					OutputPins.Add(MakeShared<FJsonValueObject>(PinObj));
				}
			}

			if (Defaults->Values.Num() > 0)
			{
				NodeObj->SetObjectField(TEXT("defaults"), Defaults);
			}
			NodeObj->SetArrayField(TEXT("input_pins"), InputPins);
			NodeObj->SetArrayField(TEXT("output_pins"), OutputPins);

			NodeArray.Add(MakeShared<FJsonValueObject>(NodeObj));
		}
	}

	TSet<const UEdGraphNode*> Reachable;
	ComputeReachability(Graph, Hooks, Reachable);

	TArray<FString> DeadNodes;
	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (!Reachable.Contains(Node) && !IsEntryNode(Node))
		{
			if (const FString* Id = NodeIds.Find(Node))
			{
				DeadNodes.Add(*Id);
			}
		}
	}
	DeadNodes.Sort();

	TArray<TArray<FString>> DisconnectedSubgraphs;
	FindDisconnectedSubgraphs(Graph, Reachable, NodeIds, DisconnectedSubgraphs);

	TArray<FString> EntryPoints;
	if (Hooks.GatherEntryNodes)
	{
		for (const UEdGraphNode* EntryNode : Hooks.GatherEntryNodes(Graph))
		{
			if (const FString* Id = NodeIds.Find(EntryNode))
			{
				EntryPoints.Add(*Id);
			}
		}
	}
	EntryPoints.Sort();

	TArray<TSharedPtr<FJsonValue>> CompilerErrors;
	for (UEdGraphNode* Node : Graph->Nodes)
	{
		if (!Node->ErrorMsg.IsEmpty())
		{
			TSharedPtr<FJsonObject> Diag = MakeShared<FJsonObject>();
			Diag->SetStringField(TEXT("severity"), TEXT("error"));
			Diag->SetStringField(TEXT("code"), TEXT("graph.node_error"));
			Diag->SetStringField(TEXT("message"), Node->ErrorMsg);
			if (const FString* Id = NodeIds.Find(Node))
			{
				Diag->SetStringField(TEXT("node_id"), *Id);
			}
			CompilerErrors.Add(MakeShared<FJsonValueObject>(Diag));
		}
	}

	TSharedPtr<FJsonObject> GraphDiagnostics = MakeShared<FJsonObject>();
	if (DeadNodes.Num() > 0)
	{
		TArray<TSharedPtr<FJsonValue>> Dead;
		for (const FString& Id : DeadNodes)
		{
			Dead.Add(MakeShared<FJsonValueString>(Id));
		}
		GraphDiagnostics->SetArrayField(TEXT("dead_nodes"), Dead);
	}

	if (DisconnectedSubgraphs.Num() > 0)
	{
		TArray<TSharedPtr<FJsonValue>> Islands;
		for (const TArray<FString>& Island : DisconnectedSubgraphs)
		{
			TArray<TSharedPtr<FJsonValue>> IslandJson;
			for (const FString& Id : Island)
			{
				IslandJson.Add(MakeShared<FJsonValueString>(Id));
			}
			Islands.Add(MakeShared<FJsonValueArray>(IslandJson));
		}
		GraphDiagnostics->SetArrayField(TEXT("disconnected_subgraphs"), Islands);
	}

	if (CompilerErrors.Num() > 0)
	{
		GraphDiagnostics->SetArrayField(TEXT("errors"), CompilerErrors);
	}

	TSharedPtr<FJsonObject> GraphObj = MakeShared<FJsonObject>();
	GraphObj->SetStringField(TEXT("asset_path"), Options.AssetPath);
	GraphObj->SetStringField(TEXT("graph_id"), Options.GraphName);
	GraphObj->SetStringField(TEXT("graph_name"), Options.GraphName);
	GraphObj->SetStringField(TEXT("graph_type"), Options.GraphType);
	GraphObj->SetStringField(TEXT("schema_version"), TEXT("1.0"));
	GraphObj->SetStringField(TEXT("engine_version"), FormatEngineVersionString());
	GraphObj->SetStringField(TEXT("retrieved_at"), FDateTime::UtcNow().ToIso8601());

	TSharedPtr<FJsonObject> Fidelity = MakeShared<FJsonObject>();
	Fidelity->SetBoolField(TEXT("round_trip_supported"), Options.bRoundTripSupported);
	TArray<TSharedPtr<FJsonValue>> Lossy;
	for (const FString& Area : Options.LossyAreas)
	{
		Lossy.Add(MakeShared<FJsonValueString>(Area));
	}
	Fidelity->SetArrayField(TEXT("lossy_areas"), Lossy);
	GraphObj->SetObjectField(TEXT("fidelity"), Fidelity);

	TSharedPtr<FJsonObject> Summary = MakeShared<FJsonObject>();
	Summary->SetStringField(
		TEXT("purpose"),
		FString::Printf(TEXT("%s '%s'"), *Options.PurposeSummaryPrefix, *Options.GraphName));
	Summary->SetNumberField(TEXT("node_count"), Graph->Nodes.Num());
	GraphObj->SetObjectField(TEXT("semantic_summary"), Summary);

	if (EntryPoints.Num() > 0)
	{
		TArray<TSharedPtr<FJsonValue>> EntryJson;
		for (const FString& Ep : EntryPoints)
		{
			EntryJson.Add(MakeShared<FJsonValueString>(Ep));
		}
		GraphObj->SetArrayField(TEXT("entry_points"), EntryJson);
	}

	if (Options.bEmitNodesAndLinks)
	{
		GraphObj->SetArrayField(TEXT("nodes"), NodeArray);
		GraphObj->SetArrayField(TEXT("links"), LinkArray);
	}

	GraphObj->SetObjectField(TEXT("diagnostics"), GraphDiagnostics);
	OutResult.Graph = GraphObj;
	return true;
}
